name: strongpay
description: The StrongHands mobile wallet 
version: 0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_fonts: ^0.2.0
  shared_preferences: ^0.5.6
  retrofit: ^1.0.1+1
  mobx: ^0.4.0+1
  flutter_mobx: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: any
  retrofit_generator: ^1.0.2+2
  flutter_launcher_icons: ^0.7.4
  build_runner: ^1.7.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo_strongpay_yellow.png"

flutter:

  uses-material-design: true

  assets:
    - images/logo_stronghands.png
    - images/logo_strongpay_black.png
    - images/logo_strongpay_yellow.png
    - images/strongpay_banner.png
    - images/logo_black_strongpay_clean.png
    - images/logo_yellow_strongpay_clean.png
    - images/ic_stronghands_small.png
    - images/ic_masternode_small.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
